export default [
    "red",
    "red lighten-1",
    "red darken-1",
    "red darken-2",
    "red darken-3",
    "red darken-4",
    "red darken-5",
    "cyan",
    "cyan lighten-1",
    "cyan darken-1",
    "cyan darken-2",
    "cyan darken-3",
    "cyan darken-4",
    "cyan darken-5",
    "pink",
    "pink lighten-1",
    "pink darken-1",
    "pink darken-2",
    "pink darken-3",
    "pink darken-4",
    "pink darken-5",
    "yellow",
    "yellow darken-1",
    "yellow darken-2",
    "yellow darken-3",
    "yellow darken-4",
    "yellow darken-5",
    "purple",
    "purple lighten-1",
    "purple darken-1",
    "purple darken-2",
    "purple darken-3",
    "purple darken-4",
    "purple darken-5",
    "indigo",
    "indigo lighten-1",
    "indigo darken-1",
    "indigo darken-2",
    "indigo darken-3",
    "indigo darken-4",
    "indigo darken-5",
    "blue",
    "blue lighten-1",
    "blue darken-1",
    "blue darken-2",
    "blue darken-3",
    "blue darken-4",
    "blue darken-5",
    "teal",
    "teal lighten-1",
    "teal darken-1",
    "teal darken-2",
    "teal darken-3",
    "teal darken-4",
    "teal darken-5",
    "cyan",
    "cyan lighten-1",
    "cyan darken-1",
    "cyan darken-2",
    "cyan darken-3",
    "cyan darken-4",
    "cyan darken-5",
    "green",
    "green lighten-1",
    "green darken-1",
    "green darken-2",
    "green darken-3",
    "green darken-4",
    "green darken-5",
    "lime",
    "lime lighten-1",
    "lime darken-1",
    "lime darken-2",
    "lime darken-3",
    "lime darken-4",
    "lime darken-5",
    "amber",
    "amber lighten-1",
    "amber darken-1",
    "amber darken-2",
    "amber darken-3",
    "amber darken-4",
    "amber darken-5",
    "orange",
    "orange lighten-1",
    "orange darken-1",
    "orange darken-2",
    "orange darken-3",
    "orange darken-4",
    "orange darken-5",
    "blue-grey",
    "blue-grey lighten-1",
    "blue-grey darken-1",
    "blue-grey darken-2",
    "blue-grey darken-3",
    "blue-grey darken-4",
    "blue-grey darken-5",
    "brown",
    "brown lighten-1",
    "brown darken-1",
    "brown darken-2",
    "brown darken-3",
    "brown darken-4",
    "brown darken-5",
    "grey",
    "grey lighten-1",
    "grey darken-1",
    "grey darken-2",
    "grey darken-3",
    "grey darken-4",
    "grey darken-5",
];
